using System.IO;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;
using Live2DAction.World;

namespace Live2DAction.EditorTools
{
    // 2026-08-19, explicit user request ("3D動作遊戲不是常常有那種 障礙物跨越 或是跳躍爬高的比賽嗎
    // 怎麼設計") - first playable pass of a Flight-based checkpoint time trial, built after two
    // clarifying questions the user answered explicitly: (1) "單純計時衝刺" - no energy/resource
    // gating, pure Jump/Dodge/Flight execution skill against a stopwatch; (2) "現有空島路線" - reuse
    // an already-built ground<->sky-island route instead of a brand new area.
    //
    // 2026-08-19 follow-up, explicit user request ("你要把光環放在空島與平地之間的路線，我會用上升
    // 氣流到空中，從空中到空島的這段路線 每隔一段距離放一個光環，光環碰到時玩家會短暫被加速") - the
    // first pass clustered all 5 gates near the Portal's sky-island arrival point, which is NOT the
    // route the user actually meant. Relocated entirely: gate 0 now sits just above
    // Updraft_MainArea, and the remaining gates climb in a straight line across open air to
    // SkyIsland_Ground (~(-70, 22, -25)). Confirmed physically flyable over
    // GreyboxSceneBuilder's boundary walls (wallHeight=6f) before picking these.
    //
    // 2026-08-19 third follow-up, explicit user request ("光圈首顆起點不對 看上升氣流的頂端 從頂端
    // 前方往天空島方向開始配置光環") - gate 0 had been eyeballed at (-8,7,-8), which is neither at
    // Updraft_MainArea's actual top NOR even inside its column (its CapsuleCollider, read directly
    // off the live scene: center (-2.5,5,-6) local, height 10, radius 2, Y-axis - spans world
    // Y=[0,10] around X=-2.5,Z=-6; the old gate 0 was 5.85 units off-axis in XZ and 3 units short
    // of the actual top). Recomputed from real geometry instead of guessing: top-of-capsule =
    // (-2.5, 10, -6), gate 0 placed 3 units further along the top->SkyIsland_Ground direction from
    // there (matches "頂端前方" - ahead of the top, not sitting exactly on the collider boundary),
    // so the player is unambiguously clear of the updraft's own trigger volume before the course
    // itself takes over. Every other gate re-derived from this corrected start.
    //
    // Every gate is now ALSO a boost pad (see CheckpointGate.dashSpeed and
    // CharacterMovement.ApplyDash) per "光環碰到時玩家會短暫被加速", redesigned into a real
    // forward dash per the follow-up "經過光環時需要有向前短距離衝刺的作用" - triggers on ANY
    // touch, independent of whether TimeTrialController currently counts that touch as run
    // progress, so it still feels good to "chain" through gates out of order while exploring, not
    // just on a clean run.
    //
    // 2026-08-19 second follow-up, explicit user request ("1.金色光環太淺太薄不顯眼不夠大
    // 2.距離和數量分配不適當 3.達成目標後 顯示 完成任務!") - three fixes:
    // (1) the ring sprite itself was too pale/thin and the world-space quad too small to read
    // during fast flight - see EnsureRingSprite's own updated comment for the texture-side fix;
    // RingWorldSize doubled (4x4 -> 8x8) and CheckpointGate's upcomingGateColor alpha raised
    // 0.25 -> 0.6 so the NEXT-but-one gates ahead on the path stay clearly visible, not just the
    // single currently-"Next" one.
    // (2) GatePositions switched from 6 hand-picked points (uneven ~10-14 unit gaps, hand-guessed)
    // to 9 points generated by evenly sampling the SAME start->end line (still Updraft_MainArea's
    // liftoff point -> SkyIsland_Ground) at t=0,1/8,2/8...1, with height eased via 1-(1-t)^2 same
    // as before - gives a consistent ~7.8-8.7 unit gap between every pair, tightening the "how far
    // to the next ring" read instead of the original irregular spacing.
    // (3) TimeTrialController.FinishRun now holds a temporary "完成任務!" HUD message (see that
    // class's own comment) instead of silently resetting straight back to the per-checkpoint line.
    //
    // Gate visuals are procedurally generated (same "baked pixel math, not hand-authored art"
    // convention as every other UI ring in this project - ExecutionRing.png,
    // InvulnerabilityRipple.png), fixed-orientation (NOT billboarded like every character-attached
    // effect so far - a race gate needs to face along the flight path, not always face the
    // camera) so flying through actually reads as passing through a hoop from the approach
    // direction.
    //
    // 2026-08-20, explicit user request ("空島上兩個光還請移除" + "第一個光環比上升氣流的頂端還要
    // 低，沒有辦法穿過去，後面的光環也要對應調整") - two separate fixes to the same array:
    // (1) The last two gates (old indices 7/8) sat right on/next to the sky island itself
    // (old gate 8 doubled as "arriving at SkyIsland_Ground") - confirmed visually (a render-
    // texture screenshot of the island showed two glowing gold rings sitting on it) and removed
    // entirely; the course now ends at what was gate 6, just short of the island's edge - the
    // timed portion is the ground->sky APPROACH, actually landing is no longer part of it.
    // (2) Gate 0's old height (10.56) was only 0.56 above Updraft_MainArea's own measured
    // structural top (world Y=10, from its CapsuleCollider - center local (0,5,0) + height 10 ->
    // top = 10) - razor-thin in practice, matching the real playtested report that it couldn't
    // actually be flown through. Raised gate 0 to 12.0 (a full 2-unit clearance instead of 0.56)
    // and re-eased every remaining gate's height off that new baseline with the exact same
    // 1-(1-t)^2 curve/shape as before (t=i/8, i=0..6 now instead of i=0..8) - "後面的光環也要對應
    // 調整" - so the climb still reads as one continuous curve, just re-based higher, not a kink
    // at gate 0 alone.
    //
    // 2026-08-23, explicit user request ("現在的金色光環都是連續直線排序 我要你變成S形 總共20 任你
    // 排序 有高有低但有邏輯") - the straight-line course (7 gates, one linear lerp start->end) was
    // replaced with a proper S-curve of 20 gates for more difficulty: a lateral sine sway across
    // the flight path's own perpendicular axis (exactly one full sine period end to end - one
    // left bend, one right bend, tracing an actual "S" from a bird's-eye view) layered on top of
    // the SAME start->end line and the SAME 1-(1-t)^2 height easing this course has used since
    // 2026-08-20, plus a second, faster sine wave on top of the height (two full up/down cycles)
    // for "有高有低" without breaking the overall smooth climb - "有邏輯" is exactly why both waves
    // are pure sine functions over an even t=i/19 sampling rather than hand-placed/randomized
    // points: the shape is fully deterministic and both waves are mathematically guaranteed to
    // hit exactly zero at t=0 and t=1 (sin of an integer multiple of 2π), so gate 0 and the final
    // gate land EXACTLY on the same two positions this course has always used - Updraft_MainArea's
    // measured clearance point and the "just short of the sky island's edge" finish, both real
    // playtested constraints from the history above, are preserved untouched even though every
    // interior gate moved. See GenerateGatePositions below for the actual formula.
    internal static class SkyIslandTimeTrialSetup
    {
        private const string ScenePath = "Assets/_Project/Scenes/GreyboxTest.unity";
        private const string RingSpritePath = "Assets/_Project/UI/Textures/CheckpointGateRing.png";

        // Doubled from 4x4 - explicit user feedback ("不夠大") that the ring read as too small
        // during flythrough, especially from a distance while approaching at speed.
        private static readonly Vector2 RingWorldSize = new Vector2(8f, 8f);

        // 2026-08-20, explicit user request ("金色光環應該是碰到光環才觸發推力，而並非始終在周圍
        // 存在一道隱形的推力導致誤觸時被推引") - the previous 3.0 was a full sphere radius nearly
        // double the ring's own real visible footprint (RingWorldSize=8 world units, and the ring
        // texture's own bright band sits at normalized radius ~0.40 of that -> ~1.6 world units,
        // fading out to roughly ~2.2-2.6 by the time the soft glow is fully gone - see
        // EnsureRingSprite's own core/glow sigmas below), so the dash trigger fired well before
        // the player was anywhere near actually touching the visible ring, reading as an
        // invisible push field around it rather than a reaction to touching the gate. Pulled in
        // to sit just past the ring's real visible glow instead of doubling it - still a little
        // forgiving (a bare hit-box-exactly-matches-sprite radius would feel too stingy at flight
        // speed), but no longer detached from what's actually on screen.
        private const float TriggerRadius = 2.0f;

        // 2026-08-23, explicit user request ("變成S形 總共20 任你排序 有高有低但有邏輯") - replaces
        // the old hand-typed 7-point straight-line array with a computed 20-point S-curve. See
        // GenerateGatePositions below for the actual formula; StartPoint/EndPoint are the exact
        // same two positions this course has used since the 2026-08-20 fixes above (Updraft_
        // MainArea's measured clearance point and the "just short of the sky island's edge"
        // finish) - only the 18 interior gates actually moved.
        private static readonly Vector3 StartPoint = new Vector3(-5.33f, 13.5f, -6.82f);
        private static readonly Vector3 EndPoint = new Vector3(-52.34f, 23.81f, -20.45f);
        private const int GateCount = 20;

        // How far the path swings to either side of the straight start->end line - one full sine
        // period across the whole course traces exactly one S: swings one way, crosses back
        // through the centerline, swings the other way, ends back on-center.
        //
        // 2026-08-23, real playtested bug ("金色光環的間隔太密集 s形也不夠彎曲 沒有難度") - the first
        // pass (9f) read as a cramped slalom rather than a real S-turn: gate-to-gate spacing is a
        // direct function of this amplitude (a wider sway means each evenly-t-sampled gate covers
        // more actual world distance, since the sine's own slope is steeper), so a timid curve was
        // ALSO the cause of the too-tight spacing complaint - one fix addresses both. More than
        // doubled to 22f - open sky well above GreyboxSceneBuilder's boundary walls (wallHeight=6f;
        // every gate sits at world Y=13.5-23.8) with no other geometry nearby, confirmed by
        // re-screenshotting the new course top-down after this change.
        //
        // 2026-08-24, real playtested bug ("金色光環各自的間隔不夠遠") - still too tight even after
        // the above. StartPoint/EndPoint stay fixed (real playtested constraints - Updraft_
        // MainArea's measured clearance point and "just short of the sky island's edge", see this
        // file's class comment), so the only lever that widens EVERY gap without either point
        // moving is more amplitude - the sin() formula is mathematically guaranteed to still hit
        // exactly 0 at t=0/0.5/1 regardless of how large this gets. Raised again to 32f.
        private const float LateralSwayAmplitude = 32f;

        // A second, faster sine riding on top of the established 1-(1-t)^2 height-easing curve -
        // two full up/down cycles across the course for "有高有低", independent of the lateral
        // sway's own single cycle so the highs/lows don't always land exactly on the same gates as
        // the left/right turns (reads as one flowing 3D weave rather than two synchronized waves).
        // Scaled up alongside LateralSwayAmplitude above so the vertical weave stays proportional
        // to the now much wider horizontal one, rather than reading as flat by comparison.
        //
        // 2026-08-24 - raised alongside LateralSwayAmplitude's own same-date increase, same
        // proportionality reasoning.
        private const float VerticalWaveAmplitude = 7f;

        private static readonly Vector3[] GatePositions = GenerateGatePositions();

        private static Vector3[] GenerateGatePositions()
        {
            Vector2 startXZ = new Vector2(StartPoint.x, StartPoint.z);
            Vector2 endXZ = new Vector2(EndPoint.x, EndPoint.z);
            Vector2 mainDirXZ = (endXZ - startXZ).normalized;
            // 90-degree rotation in the XZ plane - the axis the S-curve sways across.
            Vector2 perpDirXZ = new Vector2(-mainDirXZ.y, mainDirXZ.x);

            var positions = new Vector3[GateCount];
            for (int i = 0; i < GateCount; i++)
            {
                float t = i / (float)(GateCount - 1);

                Vector2 centerlineXZ = Vector2.Lerp(startXZ, endXZ, t);
                // sin(t * 2π) is 0 at t=0, t=0.5, AND t=1 - one full S-bend that starts and ends
                // exactly on the centerline, so gate 0/the last gate never drift sideways off
                // StartPoint/EndPoint regardless of amplitude.
                float lateral = LateralSwayAmplitude * Mathf.Sin(t * Mathf.PI * 2f);
                Vector2 posXZ = centerlineXZ + perpDirXZ * lateral;

                float baseHeight = StartPoint.y + (EndPoint.y - StartPoint.y) * (1f - Mathf.Pow(1f - t, 2f));
                // sin(t * 4π) - two full cycles, also exactly 0 at t=0 and t=1 for the same reason
                // as the lateral sway above, so it never disturbs the two endpoint heights either.
                float verticalWave = VerticalWaveAmplitude * Mathf.Sin(t * Mathf.PI * 4f);

                positions[i] = new Vector3(posXZ.x, baseHeight + verticalWave, posXZ.y);
            }

            return positions;
        }

        [MenuItem("Tools/Live2DAction/Add Sky Island Time Trial Course")]
        public static void Apply()
        {
            EnsureRingSprite();

            Scene scene = EditorSceneManager.OpenScene(ScenePath, OpenSceneMode.Single);

            Sprite ringSprite = AssetDatabase.LoadAssetAtPath<Sprite>(RingSpritePath);
            if (ringSprite == null)
            {
                Debug.LogError("Checkpoint gate ring sprite not found at " + RingSpritePath + " after generation.");
                return;
            }

            GameObject existingRoot = GameObject.Find("SkyIslandTimeTrial");
            if (existingRoot != null)
            {
                Object.DestroyImmediate(existingRoot);
            }
            var root = new GameObject("SkyIslandTimeTrial");

            var gates = new CheckpointGate[GatePositions.Length];
            for (int i = 0; i < GatePositions.Length; i++)
            {
                gates[i] = CreateGate(root.transform, i, ringSprite);
            }

            var controllerGo = new GameObject("TimeTrialController");
            controllerGo.transform.SetParent(root.transform, false);
            TimeTrialController controller = controllerGo.AddComponent<TimeTrialController>();

            Text statusText = CreateStatusUi(root.transform);

            var so = new SerializedObject(controller);
            SerializedProperty gatesProp = so.FindProperty("checkpointsInOrder");
            gatesProp.arraySize = gates.Length;
            for (int i = 0; i < gates.Length; i++)
            {
                gatesProp.GetArrayElementAtIndex(i).objectReferenceValue = gates[i];
            }
            so.FindProperty("statusText").objectReferenceValue = statusText;
            so.ApplyModifiedPropertiesWithoutUndo();

            EditorSceneManager.SaveScene(scene);
            AssetDatabase.SaveAssets();
            Debug.Log($"Added Sky Island time trial course ({gates.Length} gates) - ride the updraft near Updraft_MainArea, checkpoint 0 is right where the lift hands off to flight.");
        }

        private static CheckpointGate CreateGate(Transform parent, int index, Sprite ringSprite)
        {
            var go = new GameObject($"CheckpointGate_{index}");
            go.transform.SetParent(parent, false);
            go.transform.position = GatePositions[index];

            // Faces along the incoming travel direction (previous gate -> this gate, or this ->
            // next for the very first one, which has no "previous") so the ring reads as
            // something you fly THROUGH from the approach angle, not a flat sign you glance off.
            Vector3 facing;
            if (index == 0)
            {
                facing = (GatePositions[1] - GatePositions[0]).normalized;
            }
            else
            {
                facing = (GatePositions[index] - GatePositions[index - 1]).normalized;
            }
            go.transform.rotation = Quaternion.LookRotation(facing, Vector3.up);

            SphereCollider trigger = go.AddComponent<SphereCollider>();
            trigger.isTrigger = true;
            trigger.radius = TriggerRadius;

            var canvasGo = new GameObject("Ring");
            canvasGo.transform.SetParent(go.transform, false);
            canvasGo.transform.localPosition = Vector3.zero;
            canvasGo.transform.localRotation = Quaternion.identity;

            Canvas canvas = canvasGo.AddComponent<Canvas>();
            canvas.renderMode = RenderMode.WorldSpace;
            RectTransform canvasRect = canvasGo.GetComponent<RectTransform>();
            canvasRect.sizeDelta = RingWorldSize;

            // Canvas GameObject itself carries the Image directly - a single-ring gate doesn't
            // need a separate centered child the way multi-element effects (execution indicator's
            // Ring+Dot) do.
            Image ring = canvasGo.AddComponent<Image>();
            ring.sprite = ringSprite;
            ring.color = new Color(1f, 0.85f, 0.15f, 0.6f); // overwritten immediately by CheckpointGate.SetState via TimeTrialController.RefreshGateVisuals; matches upcomingGateColor as the sane initial value
            ring.raycastTarget = false;
            ring.useSpriteMesh = true; // same square-frame-avoidance lesson as every other procedural ring this project has shipped

            CheckpointGate gate = go.AddComponent<CheckpointGate>();
            var so = new SerializedObject(gate);
            so.FindProperty("order").intValue = index;
            so.FindProperty("ringImage").objectReferenceValue = ring;
            so.ApplyModifiedPropertiesWithoutUndo();

            return gate;
        }

        // Plain Screen Space - Overlay Canvas + legacy UI.Text - this project's other UI is all
        // world-space per-character effects (health/stance/energy bars, execution indicator); a
        // course timer needs to stay readable on-screen regardless of where the camera happens to
        // be looking, so Overlay is the right call here specifically, not a style deviation.
        private static Text CreateStatusUi(Transform parent)
        {
            var canvasGo = new GameObject("TimeTrialHudCanvas");
            canvasGo.transform.SetParent(parent, false);

            Canvas canvas = canvasGo.AddComponent<Canvas>();
            canvas.renderMode = RenderMode.ScreenSpaceOverlay;
            CanvasScaler scaler = canvasGo.AddComponent<CanvasScaler>();
            scaler.uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
            scaler.referenceResolution = new Vector2(1920, 1080);
            canvasGo.AddComponent<GraphicRaycaster>();

            var textGo = new GameObject("StatusText");
            textGo.transform.SetParent(canvasGo.transform, false);
            RectTransform rect = textGo.AddComponent<RectTransform>();
            rect.anchorMin = new Vector2(0f, 1f);
            rect.anchorMax = new Vector2(0f, 1f);
            rect.pivot = new Vector2(0f, 1f);
            rect.anchoredPosition = new Vector2(24f, -24f);
            rect.sizeDelta = new Vector2(420f, 120f);

            Text text = textGo.AddComponent<Text>();
            text.font = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
            text.fontSize = 26;
            text.color = Color.white;
            text.alignment = TextAnchor.UpperLeft;
            text.text = "空島競速";

            return text;
        }

        // Procedurally bakes a bright gold "race gate" ring - same Gaussian-falloff bake as
        // ExecutionRing.png/InvulnerabilityRipple.png, recolored so it reads as a distinct
        // "objective/course" marker rather than any existing combat effect (red=execution/enemy,
        // blue=ultimate/shield, orange=stance) - gold/yellow is the universal racing-game
        // "checkpoint" color for exactly this reason.
        //
        // 2026-08-19, explicit user request ("金色光環太淺太薄不顯眼不夠大") - band thickened
        // (coreSigma 0.05->0.07, glowSigma 0.20->0.30) and the glow's own contribution strengthened
        // (0.7x->1.0x, un-attenuated), plus RingWorldSize doubled in CreateGate.
        //
        // 2026-08-19 follow-up, explicit user request ("金色光環的光暈太嚴重了") - that pass
        // overcorrected: the wide, un-attenuated glow (0.30 sigma at full strength) turned into a
        // soft fog that washed out the whole surrounding scene at any real viewing distance rather
        // than reading as a crisp ring. Core stays sharp (0.05, back down from 0.07) and the glow
        // halo pulled in tighter (0.30->0.14) with its contribution reattenuated (1.0x->0.5x) -
        // keeps the doubled RingWorldSize (that size complaint wasn't the bloom complaint) but the
        // ring itself now reads as a defined band with a modest soft edge, not a blob.
        private static void EnsureRingSprite()
        {
            string fullPath = Path.Combine(Application.dataPath, "..", RingSpritePath);

            const int size = 256;
            const float ringRadius = 0.40f;
            const float coreSigma = 0.05f;
            const float glowSigma = 0.14f;
            var ringColor = new Color(1f, 0.78f, 0.05f);

            var texture = new Texture2D(size, size, TextureFormat.RGBA32, false);
            var pixels = new Color[size * size];
            float half = size / 2f;

            for (int y = 0; y < size; y++)
            {
                for (int x = 0; x < size; x++)
                {
                    float dx = (x + 0.5f - half) / half;
                    float dy = (y + 0.5f - half) / half;
                    float d = Mathf.Sqrt(dx * dx + dy * dy);

                    float core = Mathf.Exp(-Mathf.Pow(d - ringRadius, 2f) / (2f * coreSigma * coreSigma));
                    float glow = Mathf.Exp(-Mathf.Pow(d - ringRadius, 2f) / (2f * glowSigma * glowSigma)) * 0.5f;
                    float a = Mathf.Clamp01(core + glow);

                    pixels[y * size + x] = new Color(ringColor.r, ringColor.g, ringColor.b, a);
                }
            }

            texture.SetPixels(pixels);
            texture.Apply();

            byte[] png = texture.EncodeToPNG();
            Object.DestroyImmediate(texture);

            string directory = Path.GetDirectoryName(fullPath);
            if (directory != null && !Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }
            File.WriteAllBytes(fullPath, png);

            AssetDatabase.ImportAsset(RingSpritePath);

            var importer = (TextureImporter)AssetImporter.GetAtPath(RingSpritePath);
            importer.textureType = TextureImporterType.Sprite;
            importer.spriteImportMode = SpriteImportMode.Single;
            importer.alphaIsTransparency = true;
            importer.mipmapEnabled = false;
            importer.filterMode = FilterMode.Bilinear;
            importer.textureCompression = TextureImporterCompression.Uncompressed;
            importer.spritePixelsPerUnit = 100f;
            EditorUtility.SetDirty(importer);
            importer.SaveAndReimport();
        }
    }
}
